name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Matches semantic version tags (e.g., v0.2.0)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Create Release Archive
        id: archive
        run: |
          mkdir -p archive
          git archive --format=tar.gz --prefix=zig-s3-${VERSION#v}/ -o archive/${VERSION}.tar.gz HEAD
          echo "hash=$(shasum -a 256 archive/${VERSION}.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          body: |
            Release ${{ env.VERSION }}

            ## Installation
            Add to your `build.zig.zon`:
            ```zig
            .{
                .dependencies = .{
                    .s3 = .{
                        .url = "https://github.com/${{ github.repository }}/archive/${{ env.VERSION }}.tar.gz",
                        .hash = "1220${{ steps.archive.outputs.hash }}",
                    },
                },
            }
            ```

            See CHANGELOG.md for full release notes.
          files: archive/${{ env.VERSION }}.tar.gz
          draft: false
          prerelease: false

      - name: Update README Hash
        run: |
          sed -i "s/\.hash = \".*\"/\.hash = \"1220${{ steps.archive.outputs.hash }}\"/" README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update hash in README for ${{ env.VERSION }}"
          git push 